"""
AI Helper – calls Google Gemini REST API to generate fixes for unknown issues.
Falls back gracefully if the API key is not set or the call fails.

Note: We use direct REST calls (not the google-generativeai SDK) for maximum
Python version compatibility (tested on Python 3.14+).
"""
import os
import json
import logging

import requests

logger = logging.getLogger(__name__)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL   = "gemini-1.5-flash"
GEMINI_URL     = (
    "https://generativelanguage.googleapis.com/v1beta/models/"
    f"{GEMINI_MODEL}:generateContent"
)


def _build_prompt(issue: dict) -> str:
    return (
        "You are an expert Site-Reliability Engineer (SRE) AI assistant.\n"
        "Given the following system issue detected in a production environment, "
        "suggest a concise remediation action (one or two sentences, shell command preferred).\n\n"
        f"Issue details:\n{json.dumps(issue, indent=2)}\n\n"
        "Respond ONLY with the remediation action, no extra commentary."
    )


def call_ai(issue: dict) -> dict:
    """
    Ask Gemini REST API to generate a remediation for an unrecognised issue.

    Returns a dict:
        {
            "source": "gemini" | "fallback",
            "fix": "<remediation string>",
            "explanation": "<optional detail>"
        }
    """
    if not GEMINI_API_KEY:
        return _fallback_fix(issue)

    payload = {"contents": [{"parts": [{"text": _build_prompt(issue)}]}]}
    try:
        resp = requests.post(
            GEMINI_URL,
            params={"key": GEMINI_API_KEY},
            json=payload,
            timeout=15,
        )
        resp.raise_for_status()
        data = resp.json()
        text = data["candidates"][0]["content"]["parts"][0]["text"].strip()
        return {
            "source": "gemini",
            "fix": text,
            "explanation": f"Generated by Gemini REST API ({GEMINI_MODEL})",
        }
    except Exception as exc:
        logger.warning("Gemini REST call failed: %s", exc)
        return _fallback_fix(issue)


def _fallback_fix(issue: dict) -> dict:
    """Rule-based fallback when AI is unavailable."""
    service = issue.get("service", "unknown")
    error   = (issue.get("error") or "").lower()
    cpu     = issue.get("cpu", 0)
    memory  = issue.get("memory", 0)

    if memory and int(memory) > 90:
        fix = f"Free memory: kill largest memory consumer on {service}, then restart service."
    elif cpu and int(cpu) > 90:
        fix = f"Throttle or restart {service} to reduce CPU load; investigate processes."
    elif "timeout" in error:
        fix = f"Increase timeout thresholds for {service} and check network latency."
    elif "memory" in error or "oom" in error:
        fix = f"Add swap space or scale {service} vertically; flush in-memory caches."
    elif "disk" in error:
        fix = f"Clean up disk space: delete old logs and temp files, then restart {service}."
    elif "certificate" in error or "ssl" in error:
        fix = f"Renew TLS certificate for {service} and reload the service."
    elif "connection" in error:
        fix = f"Check firewall rules and restart {service} networking stack."
    else:
        fix = f"Restart {service} and monitor for recurrence; escalate if issue persists."

    return {
        "source": "fallback",
        "fix": fix,
        "explanation": "AI unavailable – rule-based remediation applied.",
    }
